### ISSUE TITLE
Can not compile an run!

### ISSUE THREAD

**Issue by alxspiker** [Alisdair101/DirectX#1]
It just throws a bunch of unhandled exceptions.
=====================================

**Comment by Alisdair101** [comment]
Works fine over here

**Comment by alxspiker** [comment]
This is what I am getting

    Unhandled exception at 0x00D67A6B in DX11 Framework.exe: 0xC0000005: Access violation reading location 0xCDCDCDCD.

Then it takes me to Application.cpp line 547

    	if (Transparency) Transparency->Release();

I get alot of warnings on compilation but I doubt it has anything to do with the Unhandled exception.

**Comment by alxspiker** [comment]
Wait, would the directx version matter? I am running directx 12.

**Comment by Alisdair101** [comment]
It could be yes, I've had difficulty running this on different versions of DirectX

**Comment by Alisdair101** [comment]
I am running this on DirectX 11, I'm not sure how much the class libraries have been changed from DX11 to DX12. I've not tested it on DX12.

**Comment by alxspiker** [comment]
Hmm, I can try fixing the errors, I just do not program in C++ so it may be a challenge.

**Comment by Alisdair101** [comment]
If you don't mind me asking, how did you come across my profile?

**Comment by Alisdair101** [comment]
Perfectly okay with looking at my stuff, just curious

**Comment by alxspiker** [comment]
I was just out and about trying to find a game engine for my team to start out with and develop upon and I found this.

**Comment by alxspiker** [comment]
Obviously credit will be given, just would not like to start from scratch if you know what I mean.

**Comment by Alisdair101** [comment]
Ah, I wouldn't expect too much mate, I'm a student at University, this is literally me just learning the basics such as lighting, shader language, physics and such. And using Github to store my projects.

**Comment by alxspiker** [comment]
The source code is pretty great, I am just finishing my last year of high school and plan to do stuff like this as a career. I do PHP, JS, Lua, and so much more, just haven't tried out C++ yet. And if your intension was not to make the files public, https://gitlab.com is way better than Github. 100% free and has way more features than Github.

**Comment by Alisdair101** [comment]
Thank you and I'm perfectly fine with you using my code as a basis for your project, I have them up here for people to look at while I'm looking for a placement job for my placement year. I hope you get it working.

**Comment by alxspiker** [comment]
If my project gets anywhere, I will be sure to send you a link. Thank you.
